# -*- coding: utf-8 -*-
"""student_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXBg7SM05y9EGpJVIPy-OW520vb6X-Pn
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
import xgboost as xgb
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer
from xgboost import XGBRegressor

df=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

df.head()

df.info()

print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())

l=['course','gender','facility_rating','study_method','exam_difficulty','sleep_quality','internet_access']
for i in l:
    print(df[i].value_counts())

df.describe()

df = df.drop(columns=['id'])

df['course'] = df['course'].str.lower().str.strip()
df['study_method'] = df['study_method'].str.lower().str.strip()

num_cols = df.select_dtypes(include=['int64','float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])
df = df.drop_duplicates()

#visualisation

col = 'age'
plt.figure(figsize=(8, 5))
sns.histplot(df[col], bins=30, color='steelblue', kde=False, edgecolor='black')

col = 'study_hours'
plt.figure(figsize=(8, 5))
sns.histplot(df[col], bins=30, color='steelblue', kde=False, edgecolor='black')

import seaborn as sns
import matplotlib.pyplot as plt
l=['study_method','course','sleep_quality','facility_rating',
'exam_difficulty','gender','internet_access']
for col in l:
  plt.figure(figsize=(10,5))
  sns.boxplot(x=col, y='exam_score', data=df)
  plt.xticks(rotation=45)
  plt.show()

l=['study_hours','sleep_hours','class_attendance']
for col in l:
  grouped = df.groupby('study_hours')[col].mean()
  grouped.plot()
  plt.xlabel(col)
  plt.ylabel('Average Exam Score')
  plt.show()

corr = df[['age','study_hours','class_attendance','sleep_hours','exam_score']].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

categorical_cols = df.select_dtypes(include=['object']).columns

importance = {}

for col in categorical_cols:
    importance[col] = df.groupby(col)['exam_score'].mean().std()

importance = pd.Series(importance).sort_values(ascending=False)

importance.plot(kind='bar')
plt.title("Which Factors Affect Exam Score the Most")
plt.ylabel("Variation (Std Dev)")
plt.show()

# Check invalid values
print("Invalid age:", df[(df['age'] < 10) | (df['age'] > 60)].shape[0])
print("Invalid study_hours:", df[(df['study_hours'] < 0) | (df['study_hours'] > 24)].shape[0])
print("Invalid sleep_hours:", df[(df['sleep_hours'] < 0) | (df['sleep_hours'] > 24)].shape[0])
print("Invalid attendance:", df[(df['class_attendance'] < 0) | (df['class_attendance'] > 100)].shape[0])
print("Invalid score:", df[(df['exam_score'] < 0) | (df['exam_score'] > 100)].shape[0])

df['sleep_quality'] = df['sleep_quality'].map({
    'poor': 0,
    'average': 1,
    'good': 2
})

df['facility_rating'] = df['facility_rating'].map({
    'low': 0,
    'medium': 1,
    'high': 2
})

df['exam_difficulty'] = df['exam_difficulty'].map({
    'easy': 0,
    'moderate': 1,
    'hard': 2
})

df['internet_access'] = df['internet_access'].map({
    'no': 0,
    'yes': 1
})

df['effort_score'] = df['study_hours'] * df['class_attendance']
df['sleep_impact'] = df['sleep_hours'] * df['sleep_quality']
df['stress_level'] = df['exam_difficulty'] * df['study_hours']
df['digital_usage'] = df['internet_access'] * df['study_hours']
df['study_sleep_ratio'] = df['study_hours'] / (df['sleep_hours'] + 1)
df['attendance_sleep'] = df['class_attendance'] * df['sleep_quality']
df['sleep_balance'] = df['sleep_hours'] * (df['sleep_quality'] == 2).astype(int)
df['age_group'] = pd.cut(df['age'], bins=[0,18,25,40,100], labels=[0,1,2,3])
df['attendance_level'] = pd.cut(df['class_attendance'], bins=[0,60,80,100], labels=[0,1,2])

df = df[
    (df['age'].between(10, 60)) &
    (df['study_hours'].between(0, 24)) &
    (df['sleep_hours'].between(0, 24)) &
    (df['class_attendance'].between(0, 100)) &
    (df['exam_score'].between(0, 100))
]

for col in ['age','study_hours']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = np.clip(df[col], lower, upper)

df = pd.get_dummies(df, drop_first=True)

X = df.drop(columns=['exam_score'])
y = df['exam_score']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "Linear Regression": LinearRegression(),
    "Gradient Boosting": GradientBoostingRegressor(),
    "xgb":XGBRegressor(n_estimators=200, learning_rate=0.05)
}

from sklearn.metrics import r2_score, mean_absolute_error ,mean_squared_error

results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Evaluate
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    results.append({
        "Model": name,
        "R2 Score": r2,
        "MAE": mae,
        "RMSE": rmse
    })

results_df = pd.DataFrame(results)

# Sort by RMSE (LOWER is better)
results_df = results_df.sort_values(by="RMSE")

results_df

from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train,y_train)

# Predict
y_pred = xgb.predict(X_test)

    # Evaluate
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2 Score:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer, mean_squared_error
xgb = XGBRegressor(random_state=42)
param_dist = {
    "n_estimators": [100, 200, 300, 500],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "max_depth": [3, 4, 5, 6, 8],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "gamma": [0, 0.1, 0.2, 0.3],
    "reg_alpha": [0, 0.1, 1],
    "reg_lambda": [1, 1.5, 2]
}
rmse_scorer = make_scorer(
    mean_squared_error,
    squared=False  # gives RMSE directly
)
random_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=20,              # increase to 50+ if you want better results
    scoring=rmse_scorer,
    cv=3,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train, y_train)

print("Best Params:", random_search.best_params_)

best_xgb = random_search.best_estimator_

y_pred = best_xgb.predict(X_test)

from sklearn.metrics import r2_score

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("RMSE:", rmse)
print("R2:", r2)

#test

test = pd.read_csv("test.csv")

test_ids = test['id']

# Apply same cleaning
test['course'] = test['course'].str.lower().str.strip()
test['study_method'] = test['study_method'].str.lower().str.strip()

# Same encoding
test['sleep_quality'] = test['sleep_quality'].map({'poor':0,'average':1,'good':2})
test['facility_rating'] = test['facility_rating'].map({'low':0,'medium':1,'high':2})
test['exam_difficulty'] = test['exam_difficulty'].map({'easy':0,'moderate':1,'hard':2})
test['internet_access'] = test['internet_access'].map({'no':0,'yes':1})

# SAME feature engineering
test['effort_score'] = test['study_hours'] * test['class_attendance']
test['sleep_impact'] = test['sleep_hours'] * test['sleep_quality']
test['stress_level'] = test['exam_difficulty'] * test['study_hours']
test['digital_usage'] = test['internet_access'] * test['study_hours']
test['study_sleep_ratio'] = test['study_hours'] / (test['sleep_hours'] + 1)
test['attendance_sleep'] = test['class_attendance'] * test['sleep_quality']
test['sleep_balance'] = test['sleep_hours'] * (test['sleep_quality'] == 2).astype(int)
test['age_group'] = pd.cut(test['age'], bins=[0,18,25,40,100], labels=[0,1,2,3])
test['attendance_level'] = pd.cut(test['class_attendance'], bins=[0,60,80,100], labels=[0,1,2])

# One-hot encoding
test = pd.get_dummies(test, drop_first=True)

# Align columns
test = test.reindex(columns=X.columns, fill_value=0)

# Scale
test = scaler.transform(test)



predictions = best_xgb.predict(test)

submission = pd.DataFrame({
    'id': test_ids,
    'exam_score': predictions
})

submission.to_csv("submission.csv", index=False)

print("✅ Submission file created!")

import pickle
pickle.dump(scaler, open("scaler.pkl", "wb"))

import pickle
pickle.dump(model, open("best_xgb.pkl", "wb"))

# Save feature names
feature_names = X.columns.tolist()
pickle.dump(feature_names, open("features.pkl", "wb"))